### ISSUE TITLE
Upload Privacy policy document in App/website and website signup pages.

### ISSUE THREAD

**Issue by ruchin-rumsan** [esatya/rahat-documentation#40]
- Put an privacy policy link at the footer of every signup pages of [Rahat-Agency](https://github.com/esatya/rahat-agency) , [Rahat-Mobilizer](https://github.com/esatya/rahat-mobilizer), [Rahat-Vendor](https://github.com/esatya/rahat-vendor)

- Link should be described as: `By signing up you acknowledge the Privacy Policy.** LINK: https://docs.rahat.io/privacy-policy`

NOTE: Above link will be live soon.

Document details - https://docs.google.com/document/d/1ZHvw-4wgfRb0atvCkWkRohYxFwyoR3vV0OuAwun9sjc/edit

![image](https://user-images.githubusercontent.com/86782523/160083612-a16fdddd-ac43-4e00-a8c9-29cf3ee32645.png)
Add something like this. **By signing up you acknowledge the Privacy Policy.**

**Comment by ruchin-rumsan** [comment]
@Nishubade @myanzik Can you guys look into it? We will be needing this privacy policy in link in sign up - Agency, Vendor, Social Mobilizer

**Comment by myanzik** [comment]
This has beed updated on respective web-apps mentioned above
